#!/usr/bin/env python3

import sys
from netagent.client import NetAgentClient

c = NetAgentClient()

cmd = sys.argv[1] if len(sys.argv) > 1 else "status"

if cmd == "status":
    print(c.status())

elif cmd == "list":
    for iface in c.list_interfaces():
        print(iface["iface"])

else:
    print("Unknown command")
    